workflows:
  android-workflow:
    name: Android Zip Build
    environment:
      java: 17
    scripts:
      - name: Unzip Project
        script: |
          unzip -o *.zip -d android_project || true
      - name: Build Debug APK
        script: |
          PROJECT_DIR=$(dirname $(find android_project -name "settings.gradle*" | head -n 1))
          cd $PROJECT_DIR
          
          # Yeh command automatically naya aur latest gradlew file bana degi
          gradle wrapper --gradle-version 9.3.1
          chmod +x gradlew
          
          export _JAVA_OPTIONS="-Djava.awt.headless=true"
          
          # Ab hum latest wrapper ka use karke app banayenge
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android_project/**/app/build/outputs/apk/**/*.apk
