name: Android Build from Zip

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Unzip Project & Find Root
      run: |
        # Unzip karte waqt minor warnings ko ignore karne ke liye || true lagaya hai
        unzip -o *.zip -d android_project || true
        
        # Project ka main folder dhundhega
        PROJECT_DIR=$(dirname $(find android_project -name "settings.gradle*" | head -n 1))
        echo "PROJECT_PATH=$PROJECT_DIR" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build Debug APK
      run: |
        cd ${{ env.PROJECT_PATH }}
        gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: ${{ env.PROJECT_PATH }}/app/build/outputs/apk/debug/*.apk
